# Generated by Django 5.1.4 on 2025-01-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_remove_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='user',
        ),
    ]
