# Generated by Django 5.1.4 on 2025-01-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_chatmessage_recipient_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_sender',
            field=models.BooleanField(default=False),
        ),
    ]
