# Generated by Django 5.1.4 on 2025-01-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_chatmessage_deleted_for_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='deleted_for_sender',
            new_name='is_deleted_by_recipient',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
