# Generated by Django 5.1.4 on 2025-01-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_rename_deleted_for_sender_chatmessage_is_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted_by_recipient',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted_by_sender',
        ),
    ]
