# Generated by Django 5.1.4 on 2025-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_remove_chatmessage_is_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_user',
            field=models.BooleanField(default=False),
        ),
    ]
