# Generated by Django 5.1.4 on 2025-01-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_chatmessage_deleted_for_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='deleted_for_recipient',
            new_name='deleted_by_recipient',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='deleted_for_user',
            new_name='deleted_by_user',
        ),
    ]
